CREATE DATABASE PRUEBA_PRACTICANTE_JAVA;
USE PRUEBA_PRACTICANTE_JAVA;

CREATE TABLE CUENTA(
  NUMERO_CUENTA INT PRIMARY KEY AUTO_INCREMENT,
  SALDO_CUENTA DOUBLE,
  ID_TRANSACIONES_FK INT,
  TITULAR_CUENTA TEXT,
  FOREIGN KEY (ID_TRANSACIONES_FK) REFERENCES TRANSACIONES (ID_TRANSACIONES) ON DELETE CASCADE 
);
CREATE TABLE TRANSACIONES(
  ID_TRANSACIONES INT PRIMARY KEY AUTO_INCREMENT,
  NUMERO_CUENTA_FK INT,
  TIPO_TRANSACION TEXT,
  VALOR_TRANSACION DOUBLE,
  FECHA_TRANSACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);